# Generated by Django 6.1 on 2026-09-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='slug',
        ),
    ]
