# Generated by Django 6.1 on 2026-09-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_tour_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='category',
        ),
    ]
