# Generated by Django 6.1 on 2026-09-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_tour_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
