# Generated by Django 6.1 on 2026-09-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
    ]
